# Generated by Django 5.1.6 on 2025-02-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relogio_ponto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='entrada_3',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='saida_3',
            field=models.DateTimeField(null=True),
        ),
    ]
