# Generated by Django 5.1.6 on 2025-02-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relogio_ponto', '0002_alter_horario_entrada_3_alter_horario_saida_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='entrada_3',
            field=models.DateTimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='horario',
            name='saida_3',
            field=models.DateTimeField(blank=True, default=''),
        ),
    ]
