# Generated by Django 5.1.6 on 2025-02-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relogio_ponto', '0005_alter_horario_entrada_3_alter_horario_saida_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='entrada_2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='saida_1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='saida_2',
            field=models.DateTimeField(null=True),
        ),
    ]
